name: eventstateprocessor
description: A Flutter package that wrap flutter bloc package for clearer implementation
version: 1.0.1
homepage: https://github.com/extremevn/event_state_processor

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^7.1.0

dev_dependencies:
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter

flutter:
