name: eventstateprocessor
description: A Flutter package that wrap flutter bloc package for clearer implementation
version: 0.1.0
homepage: https://github.com/extremevn/event_state_processor

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^7.0.1
  pedantic: ^1.9.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
